apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fetchhostnameapp-ENVIRONMENT-BUILD_NUMBER
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fetchhostnameapp
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: fetchhostnameapp-ENVIRONMENT-BUILD_NUMBER
        image: IMAGE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
